### ISSUE TITLE
the herokuapp is down

### ISSUE THREAD

**Issue by 1upbyte** [samihan-m/discord-attachment-link-shortener#1]
also maybe a replit backup?

**Comment by samihan-m** [comment]
Yeah my free hosting hours (for all my apps) run out way too fast if I leave the deploy for this particular app on.

Will look into replit now. Didn't know they could host. Thanks for the tip!

**Comment by samihan-m** [comment]
Replit host is up at [https://dscd.link](https://dscd.link) ! Thanks for letting me know that exists. Really awesome tool.

**Comment by 1upbyte** [comment]
awesome!

**Comment by 1upbyte** [comment]
also idk if this is the place to talk about it but could it be possible for you to add support for message links?


the format is `https://discord.com/channels/SERVER_ID/CHANNEL_ID/MESSAGE_ID ` which looking at the source code should be relatively easily swapped out. if you don't have time/dont want to i can do it myself with a pr

**Comment by samihan-m** [comment]
just to keep things organized, open a new issue for it
i can definitely try to do that ill take a look
