### ISSUE TITLE
add support for message links

### ISSUE THREAD

**Issue by 1upbyte** [samihan-m/discord-attachment-link-shortener#2]
the format is `https://discord.com/channels/SERVER_ID/CHANNEL_ID/MESSAGE_ID ` which looking at the source code should be relatively easily swapped out. if you don't have time/dont want to i can do it myself with a pr

_Referencing https://github.com/samihan-m/discord-attachment-link-shortener/issues/1#issuecomment-1001818504_

**Comment by samihan-m** [comment]
check latest version - that should be added. thanks for the comment on what to add! it's nice being able to work on this "old" project of mine, and elevate it a little, ESPECIALLY if people are going to be using it. Feel free to re-open this issue if the message link shortening feature isn't working.
